/**
 * Removes leftovers from the previous implementation.
 *
 * Switching branches does not delete *untracked* files, so an earlier version's
 * folders (and their node_modules, database and uploads) can survive on disk and
 * even keep serving on port 4000. This removes them, and nothing else.
 *
 *   npm run clean:legacy
 *
 * Safe by design: it refuses to run unless the current tree is TraceBack, and
 * everything it deletes is either recoverable from git history (`git checkout
 * main`) or regenerated by `npm run setup`.
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname ?? path.dirname(new URL(import.meta.url).pathname), '..');

// Guard: only ever run inside the TraceBack layout.
const looksLikeTraceBack =
  fs.existsSync(path.join(ROOT, 'server', 'package.json')) &&
  fs.existsSync(path.join(ROOT, 'client', 'package.json')) &&
  fs.existsSync(path.join(ROOT, 'server', 'src', 'matching.js'));

if (!looksLikeTraceBack) {
  console.error(
    [
      '',
      '  ✗ Refusing to run: this does not look like the TraceBack tree.',
      '',
      '    Expected server/package.json, client/package.json and',
      '    server/src/matching.js to exist. You are probably on the old branch —',
      '    switch first:  git checkout feat/replace-with-traceback',
      '',
    ].join('\n')
  );
  process.exit(1);
}

const LEGACY = [
  'backend',
  'frontend',
  'ai-service',
  'deploy',
  'scripts',
  'docker-compose.yml',
];

const sizeOf = (target) => {
  let bytes = 0;
  const walk = (p) => {
    const st = fs.statSync(p);
    if (st.isDirectory()) for (const e of fs.readdirSync(p)) walk(path.join(p, e));
    else bytes += st.size;
  };
  try {
    walk(target);
  } catch {
    /* unreadable entries do not matter for a size estimate */
  }
  return bytes;
};

let removed = 0;
let freed = 0;

for (const name of LEGACY) {
  const target = path.join(ROOT, name);
  if (!fs.existsSync(target)) continue;
  const bytes = sizeOf(target);
  fs.rmSync(target, { recursive: true, force: true });
  removed += 1;
  freed += bytes;
  console.log(`  removed ${name.padEnd(18)} ${(bytes / 1024 / 1024).toFixed(1)} MB`);
}

if (!removed) {
  console.log('  nothing to clean — no files from the previous implementation on disk');
} else {
  console.log(
    `\n  ${removed} leftover item(s) removed, ${(freed / 1024 / 1024).toFixed(1)} MB freed.` +
      '\n  The old implementation is still in git history if you need it: git checkout main\n'
  );
}
